CREATE SEQUENCE seq_customers START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_movies START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_screens START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_shows START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_seats START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_tickets START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_payments START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_admins START WITH 1 INCREMENT BY 1;


-- select all created sequences in our schema
SELECT 'SEQUENCE NAME:  "' || sequence_name || '"' AS SEQUENCES
FROM user_sequences;